### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'patch'

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacyzpts#41]
Running
```
python legacy_zeropoints.py --camera 90prime \
--image 90prime/BOK_CP/CP20160504/ksb_160505_025629_ooi_g_v1.fits.fz
```
results in a crash that appears to be deep in the bowels of `Tractor` (but where we rended the PSF on a uniform pixel grid).  I'm putting in a hack-fix for now, but this should be tracked down.
```
Wrote zpts/90prime/CP20160504/ksb_160505_025629_ooi_g_v1-legacypipe.fits
Reading CCD 1 of 4: file 90prime/BOK_CP/CP20160504/ksb_160505_025629_ooi_g_v1.fits.fz                                                             CCD 75130033 CCD1
Faked up EXPNUM 75130033
Reading CCD 2 of 4: file 90prime/BOK_CP/CP20160504/ksb_160505_025629_ooi_g_v1.fits.fz                                                             CCD 75130033 CCD2
Faked up EXPNUM 75130033
Reading CCD 3 of 4: file 90prime/BOK_CP/CP20160504/ksb_160505_025629_ooi_g_v1.fits.fz                                                             CCD 75130033 CCD3
Faked up EXPNUM 75130033
Traceback (most recent call last):
  File "/global/homes/i/ioannis/scratch/dr8-test-regions/code/legacyzpts/py/legacyzpts/legacy_zeropoints.py", line 3016, in <module>
    main(image_list=images,args=args)
  File "/global/homes/i/ioannis/scratch/dr8-test-regions/code/legacyzpts/py/legacyzpts/legacy_zeropoints.py", line 2948, in main
    runit(F.imgfn, F.starfn_photom, F.legfn, F.annfn, **measureargs)
  File "/global/homes/i/ioannis/scratch/dr8-test-regions/code/legacyzpts/py/legacyzpts/legacy_zeropoints.py", line 2812, in runit
    create_annotated_table(legfn, annfn, measureargs['camera'], survey, psf=psf)
  File "/global/homes/i/ioannis/scratch/dr8-test-regions/code/legacyzpts/py/legacyzpts/legacy_zeropoints.py", line 275, in create_annotated_table
    normalizePsf=psf, carryOn=True)
  File "/global/cscratch1/sd/ioannis/dr8-test-regions/code/legacypipe/py/legacypipe/annotate_ccds.py", line 168, in annotate
    g = im.galaxy_norm(tim, x=x, y=y)
  File "/global/cscratch1/sd/ioannis/dr8-test-regions/code/legacypipe/py/legacypipe/image.py", line 663, in galaxy_norm
    galmod = gal.getModelPatch(tim, modelMask=mm).patch
AttributeError: 'NoneType' object has no attribute 'patch'
```

**Comment by dstndstn** [comment]
This example turns out to be a super weird WCS header in that image.
![wcs](https://user-images.githubusercontent.com/1065981/54481755-43294c00-480f-11e9-8fe5-5111b957c04b.png)

**Comment by moustakas** [comment]
This exposure was discussed on-list in `[decam-chatter 8747]`, and it was decided to not do anything special.  The image fails various `ccd_cuts` cuts, and the crash in the code was fixed using a `try:except` block.
